version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
