---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "poetry check"
      prepareCmd: "poetry version ${nextRelease.version} && poetry build"
      publishCmd: "poetry publish"
  - - "@semantic-release/git"
    - assets:
        - pyproject.toml
