site_name: StupiDB
project_name: "stupidb"
site_url: https://github.com/cpcloud/stupidb
repo_url: https://github.com/cpcloud/stupidb
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  # logo: static/img/logo_ibis.svg
  # favicon: static/img/favicon.ico
  palette:
    scheme: slate
    primary: black
    accent: lime
plugins:
  - search
  - macros
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          selection:
            docstring_style: numpy
          rendering:
            show_category_heading: true
            show_root_full_path: false
            show_root_heading: true
            show_root_toc_entry: true
            show_source: false
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html # used for the hero image
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.saneheaders
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc
nav:
  - Home: index.md
  - API Reference: api.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cpcloud/stupidb

copyright: "Copyright &copy; 2014-2022, Phillip Cloud"
