name: Automatic Rebase Dispatch
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  auto-rebase-dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          issue-number: ${{ github.event.number }}
          body: "/rebase"
